### ISSUE TITLE
Disagreement between redis an cluster-key-slot on keyslot for fancy character, patch included

### ISSUE THREAD

**Issue by dkimdon** [invertase/cluster-key-slot#3]
The character in question is:

http://www.fileformat.info/info/unicode/char/1f480/index.htm

I have run into other strange characters that are a problem as well. It looks like the string to utf8 array conversion is not working correctly somewhere. redis calculated a different hash slot and returns MOVED 9284, the client tries again at the wrong slot still. . . this repeats until the client gives up.

```
$ cat slot-bug.js 
var Redis = require('ioredis');
var cluster = new Redis.Cluster([{
    port: 30001,
    host: '127.0.0.1'
}]);
cluster.set('\uD83D\uDC80', 'SKULL');
cluster.get('\uD83D\uDC80', function(err, res) {
    if (err) {
        console.log('failed to get result');
    } else {
        console.log('Got result: ' + res);
    }
    cluster.disconnect();
});

$ node slot-bug.js 
failed to get result
Unhandled rejection Error: Too many Cluster redirections. Last error: ReplyError: MOVED 9284 127.0.0.1:30002
    at Cluster.handleError (/home/dkimdon/temp/slot-bug/node_modules/ioredis/lib/cluster/index.js:554:30)
    at Command.command.reject (/home/dkimdon/temp/slot-bug/node_modules/ioredis/lib/cluster/index.js:444:13)
    at Redis.exports.returnError (/home/dkimdon/temp/slot-bug/node_modules/ioredis/lib/redis/parser.js:75:18)
    at JavascriptReplyParser.returnError (/home/dkimdon/temp/slot-bug/node_modules/ioredis/lib/redis/parser.js:25:13)
    at JavascriptReplyParser.run (/home/dkimdon/temp/slot-bug/node_modules/redis-parser/lib/javascript.js:135:18)
    at JavascriptReplyParser.execute (/home/dkimdon/temp/slot-bug/node_modules/redis-parser/lib/javascript.js:112:10)
    at Socket.<anonymous> (/home/dkimdon/temp/slot-bug/node_modules/ioredis/lib/redis/event_handler.js:107:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
```

This fixes it for me, I didn't see where to change toUTF8Array() so I used the native node API:
```
$ cat  fix-keyslot.patch 
--- ./node_modules/cluster-key-slot/lib/index.js.orig	2017-03-30 22:52:59.403073650 -0700
+++ ./node_modules/cluster-key-slot/lib/index.js	2017-03-30 22:55:48.311166599 -0700
@@ -130,7 +130,7 @@
   var start = -1;
   var result = 0;
   var resultHash = 0;
-  var utf8 = toUTF8Array(str);
+  var utf8 = Buffer.from(str);
   var len = utf8.length;
 
   while (i < len) {
$ patch -p0  < fix-keyslot.patch 
patching file ./node_modules/cluster-key-slot/lib/index.js
$ node slot-bug.js 
Got result: SKULL
$ 
```
Looks like redis thinks the slot should be 9284:
``` 
127.0.0.1:30001> cluster keyslot 💀
(integer) 9284
127.0.0.1:30001> 
```
Adding this to the cluster-key-slot tests:
```
$ git diff
diff --git a/test/hash.spec.js b/test/hash.spec.js
index 9d07289..7c18291 100644
--- a/test/hash.spec.js
+++ b/test/hash.spec.js
@@ -21,6 +21,7 @@ var tests = {
   '漢字': 14191,
   '汉字': 16196,
   '호텔': 4350,
+  '\uD83D\uDC80': 9284, // SKULL, UTF-8 (hex) 0xF0 0x9F 0x92 0x80 (f09f9280)
   '\uD800\uDC00': 11620 // surrogate pair
 };
```
Unpatched version of cluster-key-slot fails the test:
 ```
$ npm test
  1) single hash: generate() generate a correct hash from string:

      AssertionError: 💀 - generated invalid hash: 550
      + expected - actual

      -550
      +9284
      
      at assertHash (test/hash.spec.js:42:10)
      at Array.forEach (native)
      at Context.<anonymous> (test/hash.spec.js:47:24)
. . . 
```
Patched version works:
```
$ patch ./lib/index.js < ~/temp/slot-bug/fix-keyslot.patch 
patching file ./lib/index.js
$ npm test

> cluster-key-slot@1.0.8 test /home/dkimdon/src/cluster-key-slot
> node ./node_modules/istanbul/lib/cli.js cover --preserve-comments ./node_modules/mocha/bin/_mocha -- -R spec



  single hash: generate()
    ✓ generate a correct hash from string

  multiple hashes: generateMulti()
    ✓ generate a correct hash from multiple strings
    ✓ returns -1 if any of the keys generates a different hash slot than the rest


  3 passing (7ms)

. . . 
```

**Comment by luin** [comment]
@Salakar Where are we on this issue?

**Comment by Salakar** [comment]
@dkimdon @luin just pushed a fix up for this - sorry it took so long, will publish a patch release shortly after CI runs.

**Comment by Salakar** [comment]
Ok tests are all good (0.10 + 0.12 failing due to a eslint library issue but the tests themselves pass on the CI logs)

v1.0.9 has been published to npm 👍
